# Generated by Django 4.1.6 on 2023-04-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='registerdata',
            name='mobilenumber',
            field=models.CharField(default='', max_length=13, primary_key=True, serialize=False),
        ),
    ]
