# Generated by Django 4.1.6 on 2023-04-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actapp', '0002_remove_registerdata_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='operatorregister',
            fields=[
                ('user_name', models.CharField(max_length=100)),
                ('mobilenumber', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('email_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('created_on', models.CharField(default='', max_length=100)),
                ('created_by', models.CharField(default='', max_length=100)),
                ('registerdate', models.CharField(default='', max_length=100)),
                ('softdelete', models.IntegerField(default=0)),
            ],
        ),
    ]
