# Generated by Django 4.1.6 on 2023-04-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actapp', '0004_rename_mobilenumber_operatorregister_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatorregister',
            old_name='email_id',
            new_name='Operatoremail_id',
        ),
        migrations.RenameField(
            model_name='operatorregister',
            old_name='mobile_number',
            new_name='Operatormobile_number',
        ),
        migrations.RenameField(
            model_name='operatorregister',
            old_name='password',
            new_name='Operatorpassword',
        ),
        migrations.RenameField(
            model_name='operatorregister',
            old_name='role',
            new_name='Operatorrole',
        ),
        migrations.RenameField(
            model_name='operatorregister',
            old_name='user_name',
            new_name='Operatoruser_name',
        ),
    ]
