# Generated by Django 4.1.6 on 2023-04-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actapp', '0006_mentors_rename_operatorrole_operatorregister_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Descrpition', models.CharField(max_length=10000)),
                ('link', models.CharField(max_length=1000)),
                ('thumbnail', models.CharField(default='onimage.png', max_length=225)),
                ('Updatetime', models.CharField(default='', max_length=100)),
                ('softdelete', models.IntegerField(default=0)),
            ],
        ),
    ]
